// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace XeroProject.PageObjects.Sales.RepeatingInvoiceCompleteClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class RepeatingInvoiceComplete
    {
        
        #region Properties
        public UIXeroInvoicesInternetWindow UIXeroInvoicesInternetWindow
        {
            get
            {
                if ((this.mUIXeroInvoicesInternetWindow == null))
                {
                    this.mUIXeroInvoicesInternetWindow = new UIXeroInvoicesInternetWindow();
                }
                return this.mUIXeroInvoicesInternetWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIXeroInvoicesInternetWindow mUIXeroInvoicesInternetWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIXeroInvoicesInternetWindow : BrowserWindow
    {
        
        public UIXeroInvoicesInternetWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Xero | Invoices - Internet Explorer";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Xero | Invoices - Internet Explorer");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIXeroInvoicesDocument UIXeroInvoicesDocument
        {
            get
            {
                if ((this.mUIXeroInvoicesDocument == null))
                {
                    this.mUIXeroInvoicesDocument = new UIXeroInvoicesDocument(this);
                }
                return this.mUIXeroInvoicesDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIXeroInvoicesDocument mUIXeroInvoicesDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIXeroInvoicesDocument : HtmlDocument
    {
        
        public UIXeroInvoicesDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = "ext-gen6";
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Xero | Invoices";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/AccountsReceivable/SearchRepeating.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://go.xero.com/AccountsReceivable/SearchRepeating.aspx";
            this.WindowTitles.Add("Xero | Invoices - Internet Explorer");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UITestCompanyHyperlink
        {
            get
            {
                if ((this.mUITestCompanyHyperlink == null))
                {
                    this.mUITestCompanyHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUITestCompanyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "ext-gen44";
                    this.mUITestCompanyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUITestCompanyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUITestCompanyHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "TestCompany";
                    this.mUITestCompanyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/RepeatTransactions/Edit.aspx";
                    this.mUITestCompanyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUITestCompanyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "https://go.xero.com/RepeatTransactions/Edit.aspx?invoiceID=6ed998bb-b326-4d17-abf" +
                        "0-85846f2078b5&type=AR";
                    this.mUITestCompanyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "nav";
                    this.mUITestCompanyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"nav\" id=\"ext-gen44\" href=\"/Repeat";
                    this.mUITestCompanyHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "89";
                    this.mUITestCompanyHyperlink.WindowTitles.Add("Xero | Invoices - Internet Explorer");
                    #endregion
                }
                return this.mUITestCompanyHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUITestCompanyHyperlink;
        #endregion
    }
}
